"""add image

Revision ID: 64de14d657a9
Revises: d50a306ec05d
Create Date: 2025-03-10 10:52:28.090180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64de14d657a9'
down_revision = 'd50a306ec05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('date_activity_options', schema=None) as batch_op:
        batch_op.alter_column('activity_title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('date_meal_options', schema=None) as batch_op:
        batch_op.alter_column('meal_title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('date_meeting_locations', schema=None) as batch_op:
        batch_op.alter_column('location_title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('date_meeting_locations', schema=None) as batch_op:
        batch_op.alter_column('location_title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('date_meal_options', schema=None) as batch_op:
        batch_op.alter_column('meal_title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('date_activity_options', schema=None) as batch_op:
        batch_op.alter_column('activity_title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
