"""add uuid

Revision ID: 65d169ec3004
Revises: cf47b84c4a90
Create Date: 2025-03-17 18:14:23.858608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d169ec3004'
down_revision = 'cf47b84c4a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('date_activity_options', schema=None) as batch_op:
        batch_op.alter_column('form_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'date_form', ['form_id'], ['id'])

    with op.batch_alter_table('date_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('date_meal_options', schema=None) as batch_op:
        batch_op.alter_column('form_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'date_form', ['form_id'], ['id'])

    with op.batch_alter_table('date_meeting_locations', schema=None) as batch_op:
        batch_op.alter_column('form_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'date_form', ['form_id'], ['id'])

    with op.batch_alter_table('date_responses', schema=None) as batch_op:
        batch_op.alter_column('form_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'date_form', ['form_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('date_responses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('form_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('date_meeting_locations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('form_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('date_meal_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('form_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('date_form', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('date_activity_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('form_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
