"""devided python files

Revision ID: 938dcbb1624c
Revises: 6d55ffb1bac6
Create Date: 2025-03-07 09:32:24.302586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938dcbb1624c'
down_revision = '6d55ffb1bac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('body')

    # ### end Alembic commands ###
