"""Remove response_yes_no from Date_form

Revision ID: cf47b84c4a90
Revises: 64de14d657a9
Create Date: 2025-03-12 18:07:25.679088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf47b84c4a90'
down_revision = '64de14d657a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('date_form', schema=None) as batch_op:
        batch_op.drop_column('response_yes_no')

    with op.batch_alter_table('date_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_yes_no', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('date_responses', schema=None) as batch_op:
        batch_op.drop_column('response_yes_no')

    with op.batch_alter_table('date_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_yes_no', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
