"""modified date type

Revision ID: d50a306ec05d
Revises: ec022d7fd16e
Create Date: 2025-03-07 11:52:30.880829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50a306ec05d'
down_revision = 'ec022d7fd16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('date_activity_options', schema=None) as batch_op:
        batch_op.alter_column('activity_title',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('activity_image',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('date_meal_options', schema=None) as batch_op:
        batch_op.alter_column('meal_title',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('meal_image',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('date_meeting_locations', schema=None) as batch_op:
        batch_op.alter_column('location_title',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('date_meeting_locations', schema=None) as batch_op:
        batch_op.alter_column('location_title',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('date_meal_options', schema=None) as batch_op:
        batch_op.alter_column('meal_image',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('meal_title',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('date_activity_options', schema=None) as batch_op:
        batch_op.alter_column('activity_image',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('activity_title',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
