"""Create date_form table

Revision ID: ec022d7fd16e
Revises: 938dcbb1624c
Create Date: 2025-03-07 11:25:45.236843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec022d7fd16e'
down_revision = '938dcbb1624c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_activity_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('activity_title', sa.Integer(), nullable=True),
    sa.Column('activity_image', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('date_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('partner_name', sa.String(length=100), nullable=False),
    sa.Column('response_yes_no', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('date_meal_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('meal_title', sa.Integer(), nullable=True),
    sa.Column('meal_image', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('date_meeting_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('location_title', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('date_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('selected_meal_1', sa.Integer(), nullable=True),
    sa.Column('selected_meal_2', sa.Integer(), nullable=True),
    sa.Column('selected_activity_1', sa.Integer(), nullable=True),
    sa.Column('selected_activity_2', sa.Integer(), nullable=True),
    sa.Column('selected_location', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('body', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='post_pkey')
    )
    op.drop_table('date_responses')
    op.drop_table('date_meeting_locations')
    op.drop_table('date_meal_options')
    op.drop_table('date_form')
    op.drop_table('date_activity_options')
    # ### end Alembic commands ###
