"""Reset migration

Revision ID: f17e72bffd7b
Revises: 
Create Date: 2025-03-19 02:57:23.629706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17e72bffd7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('partner_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('date_activity_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('activity_title', sa.String(length=50), nullable=False),
    sa.Column('activity_image', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['date_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('date_meal_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('meal_title', sa.String(length=50), nullable=False),
    sa.Column('meal_image', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['date_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('date_meeting_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('location_title', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['date_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('date_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('response_yes_no', sa.Boolean(), nullable=True),
    sa.Column('selected_meal_1', sa.Integer(), nullable=True),
    sa.Column('selected_meal_2', sa.Integer(), nullable=True),
    sa.Column('selected_activity_1', sa.Integer(), nullable=True),
    sa.Column('selected_activity_2', sa.Integer(), nullable=True),
    sa.Column('selected_location', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['date_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('date_responses')
    op.drop_table('date_meeting_locations')
    op.drop_table('date_meal_options')
    op.drop_table('date_activity_options')
    op.drop_table('user')
    op.drop_table('date_form')
    # ### end Alembic commands ###
