name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main  # main ブランチに push されたら実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: コードを取得
        uses: actions/checkout@v3

      - name: Python をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # EC2 に合わせる

      - name: 仮想環境を作成 & 依存関係をインストール
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: テストの実行
        run: |
          source venv/bin/activate
          pytest  # `pytest` を使用する場合

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSHでEC2にデプロイ
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/DateMe  # Flaskアプリのディレクトリへ移動
            git pull origin main
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            sudo systemctl restart flask-app  # systemd で Flask を管理している場合

